project:
  type: website
  output-dir: docs
  
freeze: auto

website:
  title: "Kisung You"
  description: "Personal Website."
  site-url: https://kisungyou.com
  open-graph: true
  twitter-card: 
    creator: "@kisung_you"
    site: "@kisung_you"
    card-style: "summary_large_image"
  navbar:
    background: primary
    search: true
    type: textbox
    pinned: true # Makes the navbar stay fixed at the top
    right:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publication.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Software"
        file: software.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "글"
        file: blog_kr.qmd
  page-footer: "© Kisung You 2021-2025"
  page-navigation: true

format:
  html:
    #theme: flatly # {simplex : minimal}
    #theme:
    #  light: flatly
    #  dark: darkly
    theme: flatly
    fontsize: 1.1em
    linestretch: 1.75
    css: styles.css
    #toc: true
    toc: false
    toc-dept: 4
    toc-title: "Contents"
    html-math-method: mathjax # katex
    highlight-style: github

editor: source

execute:
  cache: true # uses caching for faster builds