---
title: "Monte Carlo computation of $L_p$ distance between two densities on the unit hypersphere"
author: "Kisung You"
description: " " 
date: 2022-08-09
categories:
  - notes
  - geometric statistics
  - computation
format: 
  html:
    df-print: paged
    toc: true
engine: knitr
citation: false
comments: false
bibliography: bib-for-note001.bib
biblio-style: plain
google-scholar: true
number-sections: false
---

# Problem Statement

A $d$-dimensional unit hypersphere $\mathbb{S}^d = \lbrace x \in \mathbb{R}^{d+1}~|~ \|x\|_2^2 = \sum_{i=1}^{d+1} x_i^2 = 1\rbrace$ is one of the standard mathematical spaces in the field of [objected-oriented data analysis](https://doi.org/10.1201/9781351189675) [@marron_2021_ObjectOrientedData]. Let $\mathcal{P}(\mathbb{S}^d)$ denote a space of probability densities on $\mathbb{S}^d$. For two densities $f,g\in\mathcal{P}(\mathbb{S}^d)$, it is frequently needed to measure dissimilarity between the two. Unfortunately, even for the most well-known distributions on the hypersphere, analytic formula for any discrepancy measure is rarely available, leading to require numerical schemes for approximation. Here we focus on $L_p$ distance between the two densities, 
$$
L_p (f,g) = \left( \int_{\mathbb{S}^d} |f(x) - g(x)|^p \right)^{1/p}
$$ {#eq-objective} 
and we show how to combine Monte Carlo way of integration by means of [importance sampling](https://en.wikipedia.org/wiki/Importance_sampling) to approximate @eq-objective.

# Computation

Importance sampling requires a proposal density. The easiest choice is to use uniform density $u(x)$ as an importance proposal since sampling from $u(x)$ is trivial. First, take a random sample from standard normal distribution $x \sim \mathcal{N}(0,I)$ in $\mathbb{R}^{d+1}$. Then, the rest is to take $L_2$ normalization, i.e., $x \leftarrow x / \|x\|_2$, which makes a sampled vector to have a unit norm. Given the sample generation process, we have the following 
$$\begin{aligned}
L_p (f,g)^p &= \int_{\mathbb{S}^d} |f(x)-g(x)|^p dx \\ 
&= \int_{\mathbb{S}^d} \frac{|f(x)-g(x)|^p}{u(x)} u(x)  dx \\
&= \mathbb{E}_{u(x)} \left\lbrack \frac{|f(x)-g(x)|^p}{u(x)} \right\rbrack\\
&\approx \frac{1}{N} \sum_{n=1}^N \frac{|f(x)-g(x)|^p}{u(x)} \,\,\textrm{for}\,\, x_n \overset{iid}{\sim} u(x),
\end{aligned}
$$ where the last term gets better approximation as $N\rightarrow \infty$.

# References {.unnumbered .unlisted}

::: {#refs}
:::